#!/usr/bin/env python3
from __future__ import annotations

from datetime import datetime, timezone

from lib import (
    ValidationError,
    append_message,
    approved_claims_tex_path,
    claim_registry_path,
    latex_escape_claim_text,
    load_claim_registry,
    repo_root,
    scaffold_lock,
)


def render_claims(registry: dict) -> str:
    lines = [
        "% Auto-generated by scripts/synthesize_working_paper.py.",
        "% Do not edit claim keys here by hand; update workstream reports and claim_registry.json instead.",
        "",
    ]
    claims = registry.get("claims", [])
    if not claims:
        lines.extend([
            "\\noindent No approved claims have been synthesized yet.",
            "",
        ])
        return "\n".join(lines)

    for claim in claims:
        if claim.get("status") != "approved":
            continue
        claim_key = str(claim["claim_key"])
        text = latex_escape_claim_text(str(claim.get("text", "")))
        source = latex_escape_claim_text(str(claim.get("source_report", "")))
        review_round = latex_escape_claim_text(str(claim.get("review_round", "")))
        lines.append(f"\\approvedclaim{{{claim_key}}}{{{text}}}")
        lines.append(f"\\claimnote{{source: {source}; review round: {review_round}}}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    try:
        with scaffold_lock():
            registry = load_claim_registry()
            output = render_claims(registry)
            approved_claims_tex_path().write_text(output, encoding="utf-8")
            append_message(
                "working_paper_synthesized",
                None,
                "Updated approved claims LaTeX fragment from claim registry.",
                claim_registry=str(claim_registry_path().relative_to(repo_root())),
                approved_claims_tex=str(approved_claims_tex_path().relative_to(repo_root())),
                synthesized_at=datetime.now(timezone.utc).isoformat(),
            )
    except ValidationError as exc:
        print(exc)
        return 1

    print(f"Updated {approved_claims_tex_path()}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
